services:
  - type: web
    name: doce-encanto
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        value: 20.11.1
